/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsAndConditionsRouteImport } from './routes/terms-and-conditions'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as DisclaimerRouteImport } from './routes/disclaimer'
import { Route as CookiePolicyRouteImport } from './routes/cookie-policy'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AutomationsRouteImport } from './routes/automations'
import { Route as AiEmployeesRouteImport } from './routes/ai-employees'
import { Route as AiAuditRouteImport } from './routes/ai-audit'
import { Route as AccessibilityStatementRouteImport } from './routes/accessibility-statement'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AiEmployeesIndexRouteImport } from './routes/ai-employees.index'
import { Route as AiEmployeesAiReceptionistRouteImport } from './routes/ai-employees.ai-receptionist'

const TermsAndConditionsRoute = TermsAndConditionsRouteImport.update({
  id: '/terms-and-conditions',
  path: '/terms-and-conditions',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclaimerRoute = DisclaimerRouteImport.update({
  id: '/disclaimer',
  path: '/disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiePolicyRoute = CookiePolicyRouteImport.update({
  id: '/cookie-policy',
  path: '/cookie-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomationsRoute = AutomationsRouteImport.update({
  id: '/automations',
  path: '/automations',
  getParentRoute: () => rootRouteImport,
} as any)
const AiEmployeesRoute = AiEmployeesRouteImport.update({
  id: '/ai-employees',
  path: '/ai-employees',
  getParentRoute: () => rootRouteImport,
} as any)
const AiAuditRoute = AiAuditRouteImport.update({
  id: '/ai-audit',
  path: '/ai-audit',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessibilityStatementRoute = AccessibilityStatementRouteImport.update({
  id: '/accessibility-statement',
  path: '/accessibility-statement',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AiEmployeesIndexRoute = AiEmployeesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AiEmployeesRoute,
} as any)
const AiEmployeesAiReceptionistRoute =
  AiEmployeesAiReceptionistRouteImport.update({
    id: '/ai-receptionist',
    path: '/ai-receptionist',
    getParentRoute: () => AiEmployeesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accessibility-statement': typeof AccessibilityStatementRoute
  '/ai-audit': typeof AiAuditRoute
  '/ai-employees': typeof AiEmployeesRouteWithChildren
  '/automations': typeof AutomationsRoute
  '/contact': typeof ContactRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/disclaimer': typeof DisclaimerRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/ai-employees/ai-receptionist': typeof AiEmployeesAiReceptionistRoute
  '/ai-employees/': typeof AiEmployeesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accessibility-statement': typeof AccessibilityStatementRoute
  '/ai-audit': typeof AiAuditRoute
  '/automations': typeof AutomationsRoute
  '/contact': typeof ContactRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/disclaimer': typeof DisclaimerRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/ai-employees/ai-receptionist': typeof AiEmployeesAiReceptionistRoute
  '/ai-employees': typeof AiEmployeesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accessibility-statement': typeof AccessibilityStatementRoute
  '/ai-audit': typeof AiAuditRoute
  '/ai-employees': typeof AiEmployeesRouteWithChildren
  '/automations': typeof AutomationsRoute
  '/contact': typeof ContactRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/disclaimer': typeof DisclaimerRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/ai-employees/ai-receptionist': typeof AiEmployeesAiReceptionistRoute
  '/ai-employees/': typeof AiEmployeesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accessibility-statement'
    | '/ai-audit'
    | '/ai-employees'
    | '/automations'
    | '/contact'
    | '/cookie-policy'
    | '/disclaimer'
    | '/privacy-policy'
    | '/sitemap.xml'
    | '/terms-and-conditions'
    | '/ai-employees/ai-receptionist'
    | '/ai-employees/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accessibility-statement'
    | '/ai-audit'
    | '/automations'
    | '/contact'
    | '/cookie-policy'
    | '/disclaimer'
    | '/privacy-policy'
    | '/sitemap.xml'
    | '/terms-and-conditions'
    | '/ai-employees/ai-receptionist'
    | '/ai-employees'
  id:
    | '__root__'
    | '/'
    | '/accessibility-statement'
    | '/ai-audit'
    | '/ai-employees'
    | '/automations'
    | '/contact'
    | '/cookie-policy'
    | '/disclaimer'
    | '/privacy-policy'
    | '/sitemap.xml'
    | '/terms-and-conditions'
    | '/ai-employees/ai-receptionist'
    | '/ai-employees/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccessibilityStatementRoute: typeof AccessibilityStatementRoute
  AiAuditRoute: typeof AiAuditRoute
  AiEmployeesRoute: typeof AiEmployeesRouteWithChildren
  AutomationsRoute: typeof AutomationsRoute
  ContactRoute: typeof ContactRoute
  CookiePolicyRoute: typeof CookiePolicyRoute
  DisclaimerRoute: typeof DisclaimerRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsAndConditionsRoute: typeof TermsAndConditionsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms-and-conditions': {
      id: '/terms-and-conditions'
      path: '/terms-and-conditions'
      fullPath: '/terms-and-conditions'
      preLoaderRoute: typeof TermsAndConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclaimer': {
      id: '/disclaimer'
      path: '/disclaimer'
      fullPath: '/disclaimer'
      preLoaderRoute: typeof DisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookie-policy': {
      id: '/cookie-policy'
      path: '/cookie-policy'
      fullPath: '/cookie-policy'
      preLoaderRoute: typeof CookiePolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automations': {
      id: '/automations'
      path: '/automations'
      fullPath: '/automations'
      preLoaderRoute: typeof AutomationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-employees': {
      id: '/ai-employees'
      path: '/ai-employees'
      fullPath: '/ai-employees'
      preLoaderRoute: typeof AiEmployeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-audit': {
      id: '/ai-audit'
      path: '/ai-audit'
      fullPath: '/ai-audit'
      preLoaderRoute: typeof AiAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accessibility-statement': {
      id: '/accessibility-statement'
      path: '/accessibility-statement'
      fullPath: '/accessibility-statement'
      preLoaderRoute: typeof AccessibilityStatementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-employees/': {
      id: '/ai-employees/'
      path: '/'
      fullPath: '/ai-employees/'
      preLoaderRoute: typeof AiEmployeesIndexRouteImport
      parentRoute: typeof AiEmployeesRoute
    }
    '/ai-employees/ai-receptionist': {
      id: '/ai-employees/ai-receptionist'
      path: '/ai-receptionist'
      fullPath: '/ai-employees/ai-receptionist'
      preLoaderRoute: typeof AiEmployeesAiReceptionistRouteImport
      parentRoute: typeof AiEmployeesRoute
    }
  }
}

interface AiEmployeesRouteChildren {
  AiEmployeesAiReceptionistRoute: typeof AiEmployeesAiReceptionistRoute
  AiEmployeesIndexRoute: typeof AiEmployeesIndexRoute
}

const AiEmployeesRouteChildren: AiEmployeesRouteChildren = {
  AiEmployeesAiReceptionistRoute: AiEmployeesAiReceptionistRoute,
  AiEmployeesIndexRoute: AiEmployeesIndexRoute,
}

const AiEmployeesRouteWithChildren = AiEmployeesRoute._addFileChildren(
  AiEmployeesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccessibilityStatementRoute: AccessibilityStatementRoute,
  AiAuditRoute: AiAuditRoute,
  AiEmployeesRoute: AiEmployeesRouteWithChildren,
  AutomationsRoute: AutomationsRoute,
  ContactRoute: ContactRoute,
  CookiePolicyRoute: CookiePolicyRoute,
  DisclaimerRoute: DisclaimerRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsAndConditionsRoute: TermsAndConditionsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
