/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsAndConditionsRouteImport } from './routes/terms-and-conditions'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as DisclaimerRouteImport } from './routes/disclaimer'
import { Route as CookiePolicyRouteImport } from './routes/cookie-policy'
import { Route as AccessibilityStatementRouteImport } from './routes/accessibility-statement'
import { Route as IndexRouteImport } from './routes/index'

const TermsAndConditionsRoute = TermsAndConditionsRouteImport.update({
  id: '/terms-and-conditions',
  path: '/terms-and-conditions',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclaimerRoute = DisclaimerRouteImport.update({
  id: '/disclaimer',
  path: '/disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiePolicyRoute = CookiePolicyRouteImport.update({
  id: '/cookie-policy',
  path: '/cookie-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessibilityStatementRoute = AccessibilityStatementRouteImport.update({
  id: '/accessibility-statement',
  path: '/accessibility-statement',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accessibility-statement': typeof AccessibilityStatementRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/disclaimer': typeof DisclaimerRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accessibility-statement': typeof AccessibilityStatementRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/disclaimer': typeof DisclaimerRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accessibility-statement': typeof AccessibilityStatementRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/disclaimer': typeof DisclaimerRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accessibility-statement'
    | '/cookie-policy'
    | '/disclaimer'
    | '/privacy-policy'
    | '/sitemap.xml'
    | '/terms-and-conditions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accessibility-statement'
    | '/cookie-policy'
    | '/disclaimer'
    | '/privacy-policy'
    | '/sitemap.xml'
    | '/terms-and-conditions'
  id:
    | '__root__'
    | '/'
    | '/accessibility-statement'
    | '/cookie-policy'
    | '/disclaimer'
    | '/privacy-policy'
    | '/sitemap.xml'
    | '/terms-and-conditions'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccessibilityStatementRoute: typeof AccessibilityStatementRoute
  CookiePolicyRoute: typeof CookiePolicyRoute
  DisclaimerRoute: typeof DisclaimerRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsAndConditionsRoute: typeof TermsAndConditionsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms-and-conditions': {
      id: '/terms-and-conditions'
      path: '/terms-and-conditions'
      fullPath: '/terms-and-conditions'
      preLoaderRoute: typeof TermsAndConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclaimer': {
      id: '/disclaimer'
      path: '/disclaimer'
      fullPath: '/disclaimer'
      preLoaderRoute: typeof DisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookie-policy': {
      id: '/cookie-policy'
      path: '/cookie-policy'
      fullPath: '/cookie-policy'
      preLoaderRoute: typeof CookiePolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accessibility-statement': {
      id: '/accessibility-statement'
      path: '/accessibility-statement'
      fullPath: '/accessibility-statement'
      preLoaderRoute: typeof AccessibilityStatementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccessibilityStatementRoute: AccessibilityStatementRoute,
  CookiePolicyRoute: CookiePolicyRoute,
  DisclaimerRoute: DisclaimerRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsAndConditionsRoute: TermsAndConditionsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
